Description: >
  Author: Abdurrazaq Ogunlade
  This is a template that setup cloud resource
Parameters:
  EnvironmentName:
    Description: An Environment name that will be prefixed to resources
    Type: String
  ServerAmi:
    Description: Image to be use by the sever
    Type: String
  VpcID:
    Description: Vpc Id to be use to the security group
Resources:
  EC2Instance:
    Type: 'AWS::EC2::Instance'
    Properties:
      SecurityGroups:
        - !Ref InstanceSecurityGroup
      KeyName: oregon-credentials
      ImageId: !Ref ServerAmi
      Tags:
        - key: Name
          Value: !Ref EnvironmentName
  InstanceSecurityGroup:
   Type: 'AWS::EC2::SecurityGroup'
   Properties:
      GroupDescription: Enable SSH access via port 22
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: '22'
          ToPort: '22'
          CidrIp: 0.0.0.0/0
      VpcId: !Ref VpcID

