version: 2.1
commands:
  destroy_environment:
    steps:
      - run:
          name: Delete environment
          command: |
            aws cloudformation delete-stack --stack-name prod-${CIRCLE_WORKFLOW_ID}

jobs:
  build:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - run: npm i
      - save_cache:
          key: "npm-packages"
          paths:
            - /node_modules
      - run: npm run lint
  test:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - restore_cache:
          key: "npm-packages"
      - run: npm i
      - run: npm run test
  analyze:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - restore_cache:
          key: "npm-packages"
      - run: npm i
      - run: npm run test
      - run:
          name: on error
          command: echo "Error occurred when analyzing"
          when: on_fail
  create_infrastructure:
    docker: 
      - image: amazon/aws-cli
    steps:
      - checkout
      - run:
          name: Ensure backend infrastructure exist
          command: |
            aws cloudformation deploy \
            --template-file template.yml \
            --stack-name node-server-stack
  smoke_test:
    docker:
      - image: alpine:latest
    steps:
      - run: apk add --update curl
      - run:
          name: Run smoke test
          command: |
            URL = "https://blog.udacity.com" #test if blog.udacity.com is reacheable
            if curl -s --head ${URL}
            then 
              return 0
            else
              return 0  # simulate an error to cause the job to fail
            fi
workflows:
  default:
    jobs:
      - build
      - test:
          requires:
            - build
      - analyze:
          requires:
            - test
      - create_infrastructure:
          requires:
            - analyze
      - smoke_test:
          requires:
            - create_infrastructure
