version: 2.1
commands:
  destroy_environment:
    steps:
      - run:
          name: Delete environment
          command: |
            aws cloudformation delete-stack --stack-name prod-${CIRCLE_WORKFLOW_ID}
jobs:
  create_infrastructure:
    docker:
      - image: amazon/aws-cli
    steps:
      - checkout
      - run:
          name: Ensure backend infrastructure exist
          command: |
            aws cloudformation deploy \
            --template-file template.yml \
            --stack-name node-server-stack
  smoke_test:
    docker:
      - image: alpine:latest
    steps:
      - run: apk add --update curl
      - run:
          name: Run smoke test
          command: |
            URL = "https://blog.udacity.com" #test if blog.udacity.com is reacheable
            if curl -s --head ${URL}
            then
              return 0
            else
              return 0  # simulate an error to cause the job to fail
            fi
workflows:
  default:
    jobs:
      - create_infrastructure
      - smoke_test:
          requires:
            - create_infrastructure
